In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
# 1차원 배열
a = np.array([1,2,3,4])
print(a,type(a))
print(a.ndim)
print(a.shape)

[1 2 3 4] <class 'numpy.ndarray'>
1
(4,)


In [3]:
# 2차원 배열

b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b,type(b))
print(b.ndim)
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>
2
(2, 5)


In [4]:
c = np.full((2,3),5)
print(c,type(c))
print(c.ndim)
print(c.shape)

[[5 5 5]
 [5 5 5]] <class 'numpy.ndarray'>
2
(2, 3)


In [5]:
d = np.eye(10)
print(d,type(d))
print(d.ndim)
print(d.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] <class 'numpy.ndarray'>
2
(10, 10)


In [6]:
e = np.random.random((2,3))
print(e,type(e))
print(e.ndim)
print(e.shape)

[[0.22670363 0.73574989 0.91535426]
 [0.13789282 0.01861045 0.888307  ]] <class 'numpy.ndarray'>
2
(2, 3)


In [7]:
f = np.arange(10)
print(f,type(f))
print(f.ndim)
print(f.shape)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
1
(10,)


In [8]:
g = np.arange(1,10,2)
print(g,type(g))
print(g.ndim)
print(g.shape)

[1 3 5 7 9] <class 'numpy.ndarray'>
1
(5,)


In [9]:
h = np.array(np.arange(30)).reshape((5,6))
print(h,type(h))
print(h.ndim)
print(h.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] <class 'numpy.ndarray'>
2
(5, 6)


In [10]:
i = h[:2,2:]
print(i,type(i))
print(i.ndim)
print(i.shape)

[[ 2  3  4  5]
 [ 8  9 10 11]] <class 'numpy.ndarray'>
2
(2, 4)


In [11]:
x = np.array([1,2,3])
y = np.array([4,5,6])

n = y/x
print(n,type(n))
print(n.ndim)
print(n.shape)

[4.  2.5 2. ] <class 'numpy.ndarray'>
1
(3,)


In [12]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

n = np.dot(x,y)
print(n,type(n))
print(n.ndim)
print(n.shape)

[[19 22]
 [43 50]] <class 'numpy.ndarray'>
2
(2, 2)


In [13]:
sr = pd.Series((1,2,3,4,5),index = ['a','b','c','d','e'])
print(sr,type(sr))

a    1
b    2
c    3
d    4
e    5
dtype: int64 <class 'pandas.core.series.Series'>


In [14]:
print(sr.values)
print(sr.index)

[1 2 3 4 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [15]:
df = pd.DataFrame(sr)
df[1]=[6,7,8,9,0]
df

0  1
a  1  6
b  2  7
c  3  8
d  4  9
e  5  0

In [16]:
print(df.values,df.index,df.columns)

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]] Index(['a', 'b', 'c', 'd', 'e'], dtype='object') Int64Index([0, 1], dtype='int64')


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 2 columns):
0    5 non-null int64
1    5 non-null int64
dtypes: int64(2)
memory usage: 120.0+ bytes


In [33]:
data = pd.read_csv("202106_202106_연령별인구현황_월간.csv",encoding = 'utf-8')

In [35]:
df = pd.DataFrame(data)
del df['100세 이상']
df

행정구역        총인구수  연령구간인구수       0세       1세       2세  \
0        전국  (0000000000)  51,672,400  257,662  287,678  317,611  346,933   
1     서울특별시  (1100000000)   9,565,990   44,241   47,223   51,058   54,048   
2     부산광역시  (2600000000)   3,364,358   14,124   16,263   18,046   20,564   
3     대구광역시  (2700000000)   2,397,646   10,436   12,412   13,718   15,528   
4     인천광역시  (2800000000)   2,936,367   14,628   16,493   18,625   19,698   
5     광주광역시  (2900000000)   1,442,647    7,493    8,222    9,109   10,276   
6     대전광역시  (3000000000)   1,456,107    7,256    7,925    8,921    9,941   
7     울산광역시  (3100000000)   1,126,369    6,075    6,844    7,591    8,491   
8   세종특별자치시  (3600000000)     362,995    3,370    3,581    4,162    4,432   
9       경기도  (4100000000)  13,500,688   75,664   84,394   93,287  101,516   
10      강원도  (4200000000)   1,535,530    7,327    8,373    8,627    9,224   
11     충청북도  (4300000000)   1,597,503    8,194    8,970   10,091   11,020   
12     충청남도  (4400000000)   2,117,400   11,095   12,640   13,932   15,129   
13     전라북도  (4500000000)   1,794,345    7,664    8,519    9,556   10,784   
14     전라남도  (4600000000)   1,840,921    8,753    9,937   10,638   11,394   
15     경상북도  (4700000000)   2,632,401   11,976   13,662   15,109   16,555   
16     경상남도  (4800000000)   3,325,840   15,593   17,903   20,314   22,973   
17  제주특별자치도  (5000000000)     675,293    3,773    4,317    4,827    5,360   

         3세       4세       5세       6세  ...     90세     91세     92세     93세  \
0   385,649  431,448  446,115  439,671  ...  51,525  42,155  31,388  22,662   
1    59,547   66,382   68,371   67,142  ...   7,977   6,783   5,094   3,764   
2    23,055   25,859   26,621   25,962  ...   2,934   2,570   1,949   1,281   
3    17,629   19,696   20,287   19,945  ...   1,908   1,577   1,221     863   
4    22,180   24,792   25,854   25,195  ...   2,433   2,094   1,487   1,170   
5    11,633   13,141   13,465   13,553  ...   1,317     951     669     541   
6    11,244   12,384   12,937   12,732  ...   1,186   1,021     792     519   
7     9,642   10,808   11,165   11,101  ...     583     521     381     297   
8     4,756    5,244    5,392    5,195  ...     268     225     164     112   
9   112,705  126,089  130,224  126,791  ...  10,728   8,718   6,550   4,713   
10   10,084   11,025   11,467   11,454  ...   2,312   1,848   1,397     983   
11   12,105   13,324   13,448   13,592  ...   1,867   1,607   1,134     858   
12   16,661   18,560   19,242   19,087  ...   2,952   2,517   1,808   1,280   
13   11,971   13,743   14,687   14,604  ...   2,863   2,345   1,887   1,288   
14   12,336   13,815   14,354   14,461  ...   3,810   2,557   1,839   1,386   
15   18,306   20,676   21,170   21,086  ...   3,845   3,160   2,508   1,747   
16   25,979   29,380   30,614   30,802  ...   3,680   3,051   2,072   1,553   
17    5,816    6,530    6,817    6,969  ...     862     610     436     307   

       94세     95세    96세    97세    98세     99세  
0   15,432  10,829  7,530  8,085  4,616  10,777  
1    2,535   1,776  1,374  1,368    831   2,469  
2      869     610    415    399    250     758  
3      549     408    249    218    158     369  
4      774     618    376    408    240     538  
5      358     229    136    229    104     235  
6      359     232    171    170    102     202  
7      199     141    100     92     50      82  
8       62      48     27     38     22      38  
9    3,310   2,369  1,716  1,677    967   2,311  
10     789     563    403    315    191     462  
11     571     390    238    274    182     315  
12     895     580    412    457    263     519  
13     729     529    325    481    231     527  
14     970     632    491    643    303     595  
15   1,171     835    515    555    318     651  
16   1,074     713    474    440    258     506  
17     218     156    108    321    146     200  

[18 rows x 103 columns]

In [34]:
df.columns

Index(['행정구역', '총인구수', '연령구간인구수', '0세', '1세', '2세', '3세', '4세', '5세', '6세',
       ...
       '91세', '92세', '93세', '94세', '95세', '96세', '97세', '98세', '99세',
       '100세 이상'],
      dtype='object', length=104)

In [50]:
c = ['행정구역','총인구수','연령구간인구수']
for i in range(100):
    c.append(str(i)+'세')
print(c)
df.columns = c


['행정구역', '총인구수', '연령구간인구수', '0세', '1세', '2세', '3세', '4세', '5세', '6세', '7세', '8세', '9세', '10세', '11세', '12세', '13세', '14세', '15세', '16세', '17세', '18세', '19세', '20세', '21세', '22세', '23세', '24세', '25세', '26세', '27세', '28세', '29세', '30세', '31세', '32세', '33세', '34세', '35세', '36세', '37세', '38세', '39세', '40세', '41세', '42세', '43세', '44세', '45세', '46세', '47세', '48세', '49세', '50세', '51세', '52세', '53세', '54세', '55세', '56세', '57세', '58세', '59세', '60세', '61세', '62세', '63세', '64세', '65세', '66세', '67세', '68세', '69세', '70세', '71세', '72세', '73세', '74세', '75세', '76세', '77세', '78세', '79세', '80세', '81세', '82세', '83세', '84세', '85세', '86세', '87세', '88세', '89세', '90세', '91세', '92세', '93세', '94세', '95세', '96세', '97세', '98세', '99세']


행정구역        총인구수  연령구간인구수       0세       1세       2세  \
0        전국  (0000000000)  51,672,400  257,662  287,678  317,611  346,933   
1     서울특별시  (1100000000)   9,565,990   44,241   47,223   51,058   54,048   
2     부산광역시  (2600000000)   3,364,358   14,124   16,263   18,046   20,564   
3     대구광역시  (2700000000)   2,397,646   10,436   12,412   13,718   15,528   
4     인천광역시  (2800000000)   2,936,367   14,628   16,493   18,625   19,698   
5     광주광역시  (2900000000)   1,442,647    7,493    8,222    9,109   10,276   
6     대전광역시  (3000000000)   1,456,107    7,256    7,925    8,921    9,941   
7     울산광역시  (3100000000)   1,126,369    6,075    6,844    7,591    8,491   
8   세종특별자치시  (3600000000)     362,995    3,370    3,581    4,162    4,432   
9       경기도  (4100000000)  13,500,688   75,664   84,394   93,287  101,516   
10      강원도  (4200000000)   1,535,530    7,327    8,373    8,627    9,224   
11     충청북도  (4300000000)   1,597,503    8,194    8,970   10,091   11,020   
12     충청남도  (4400000000)   2,117,400   11,095   12,640   13,932   15,129   
13     전라북도  (4500000000)   1,794,345    7,664    8,519    9,556   10,784   
14     전라남도  (4600000000)   1,840,921    8,753    9,937   10,638   11,394   
15     경상북도  (4700000000)   2,632,401   11,976   13,662   15,109   16,555   
16     경상남도  (4800000000)   3,325,840   15,593   17,903   20,314   22,973   
17  제주특별자치도  (5000000000)     675,293    3,773    4,317    4,827    5,360   

         3세       4세       5세       6세  ...     90세     91세     92세     93세  \
0   385,649  431,448  446,115  439,671  ...  51,525  42,155  31,388  22,662   
1    59,547   66,382   68,371   67,142  ...   7,977   6,783   5,094   3,764   
2    23,055   25,859   26,621   25,962  ...   2,934   2,570   1,949   1,281   
3    17,629   19,696   20,287   19,945  ...   1,908   1,577   1,221     863   
4    22,180   24,792   25,854   25,195  ...   2,433   2,094   1,487   1,170   
5    11,633   13,141   13,465   13,553  ...   1,317     951     669     541   
6    11,244   12,384   12,937   12,732  ...   1,186   1,021     792     519   
7     9,642   10,808   11,165   11,101  ...     583     521     381     297   
8     4,756    5,244    5,392    5,195  ...     268     225     164     112   
9   112,705  126,089  130,224  126,791  ...  10,728   8,718   6,550   4,713   
10   10,084   11,025   11,467   11,454  ...   2,312   1,848   1,397     983   
11   12,105   13,324   13,448   13,592  ...   1,867   1,607   1,134     858   
12   16,661   18,560   19,242   19,087  ...   2,952   2,517   1,808   1,280   
13   11,971   13,743   14,687   14,604  ...   2,863   2,345   1,887   1,288   
14   12,336   13,815   14,354   14,461  ...   3,810   2,557   1,839   1,386   
15   18,306   20,676   21,170   21,086  ...   3,845   3,160   2,508   1,747   
16   25,979   29,380   30,614   30,802  ...   3,680   3,051   2,072   1,553   
17    5,816    6,530    6,817    6,969  ...     862     610     436     307   

       94세     95세    96세    97세    98세     99세  
0   15,432  10,829  7,530  8,085  4,616  10,777  
1    2,535   1,776  1,374  1,368    831   2,469  
2      869     610    415    399    250     758  
3      549     408    249    218    158     369  
4      774     618    376    408    240     538  
5      358     229    136    229    104     235  
6      359     232    171    170    102     202  
7      199     141    100     92     50      82  
8       62      48     27     38     22      38  
9    3,310   2,369  1,716  1,677    967   2,311  
10     789     563    403    315    191     462  
11     571     390    238    274    182     315  
12     895     580    412    457    263     519  
13     729     529    325    481    231     527  
14     970     632    491    643    303     595  
15   1,171     835    515    555    318     651  
16   1,074     713    474    440    258     506  
17     218     156    108    321    146     200  

[18 rows x 103 columns]

In [53]:
df1 = df.set_index('행정구역')
df1

총인구수  연령구간인구수       0세       1세       2세  \
행정구역                                                                    
전국  (0000000000)       51,672,400  257,662  287,678  317,611  346,933   
서울특별시  (1100000000)     9,565,990   44,241   47,223   51,058   54,048   
부산광역시  (2600000000)     3,364,358   14,124   16,263   18,046   20,564   
대구광역시  (2700000000)     2,397,646   10,436   12,412   13,718   15,528   
인천광역시  (2800000000)     2,936,367   14,628   16,493   18,625   19,698   
광주광역시  (2900000000)     1,442,647    7,493    8,222    9,109   10,276   
대전광역시  (3000000000)     1,456,107    7,256    7,925    8,921    9,941   
울산광역시  (3100000000)     1,126,369    6,075    6,844    7,591    8,491   
세종특별자치시  (3600000000)     362,995    3,370    3,581    4,162    4,432   
경기도  (4100000000)      13,500,688   75,664   84,394   93,287  101,516   
강원도  (4200000000)       1,535,530    7,327    8,373    8,627    9,224   
충청북도  (4300000000)      1,597,503    8,194    8,970   10,091   11,020   
충청남도  (4400000000)      2,117,400   11,095   12,640   13,932   15,129   
전라북도  (4500000000)      1,794,345    7,664    8,519    9,556   10,784   
전라남도  (4600000000)      1,840,921    8,753    9,937   10,638   11,394   
경상북도  (4700000000)      2,632,401   11,976   13,662   15,109   16,555   
경상남도  (4800000000)      3,325,840   15,593   17,903   20,314   22,973   
제주특별자치도  (5000000000)     675,293    3,773    4,317    4,827    5,360   

                            3세       4세       5세       6세       7세  ...  \
행정구역                                                                ...   
전국  (0000000000)       385,649  431,448  446,115  439,671  468,444  ...   
서울특별시  (1100000000)     59,547   66,382   68,371   67,142   71,742  ...   
부산광역시  (2600000000)     23,055   25,859   26,621   25,962   27,396  ...   
대구광역시  (2700000000)     17,629   19,696   20,287   19,945   21,185  ...   
인천광역시  (2800000000)     22,180   24,792   25,854   25,195   26,777  ...   
광주광역시  (2900000000)     11,633   13,141   13,465   13,553   14,700  ...   
대전광역시  (3000000000)     11,244   12,384   12,937   12,732   13,472  ...   
울산광역시  (3100000000)      9,642   10,808   11,165   11,101   11,538  ...   
세종특별자치시  (3600000000)    4,756    5,244    5,392    5,195    5,403  ...   
경기도  (4100000000)      112,705  126,089  130,224  126,791  135,146  ...   
강원도  (4200000000)       10,084   11,025   11,467   11,454   12,523  ...   
충청북도  (4300000000)      12,105   13,324   13,448   13,592   14,562  ...   
충청남도  (4400000000)      16,661   18,560   19,242   19,087   20,271  ...   
전라북도  (4500000000)      11,971   13,743   14,687   14,604   15,884  ...   
전라남도  (4600000000)      12,336   13,815   14,354   14,461   15,824  ...   
경상북도  (4700000000)      18,306   20,676   21,170   21,086   22,384  ...   
경상남도  (4800000000)      25,979   29,380   30,614   30,802   32,348  ...   
제주특별자치도  (5000000000)    5,816    6,530    6,817    6,969    7,289  ...   

                          90세     91세     92세     93세     94세     95세    96세  \
행정구역                                                                           
전국  (0000000000)       51,525  42,155  31,388  22,662  15,432  10,829  7,530   
서울특별시  (1100000000)     7,977   6,783   5,094   3,764   2,535   1,776  1,374   
부산광역시  (2600000000)     2,934   2,570   1,949   1,281     869     610    415   
대구광역시  (2700000000)     1,908   1,577   1,221     863     549     408    249   
인천광역시  (2800000000)     2,433   2,094   1,487   1,170     774     618    376   
광주광역시  (2900000000)     1,317     951     669     541     358     229    136   
대전광역시  (3000000000)     1,186   1,021     792     519     359     232    171   
울산광역시  (3100000000)       583     521     381     297     199     141    100   
세종특별자치시  (3600000000)     268     225     164     112      62      48     27   
경기도  (4100000000)      10,728   8,718   6,550   4,713   3,310   2,369  1,716   
강원도  (4200000000)       2,312   1,848   1,397     983     789     563    403   
충청북도  (4300000000)      1,8

In [58]:
df2 = df1['서울특별시  (1100000000)']
df2##.T.plot()
##pyplot.show()

KeyError: '서울특별시  (1100000000)'